name: focusflow
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - mysqlclient
  - pip:
      - django>=4.2
      - djangorestframework
      - pytest
      - pytest-django
      - python-dotenv
