# Generated by Django 5.2 on 2025-05-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(default="member", max_length=20),
        ),
    ]
