name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install conda
      uses: conda-incubator/setup-miniconda@v3
      with:
          python-version: 3.11
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: focusflow
          environment-file: environment.yml

    - name: Run Tests
      shell: bash -el {0}
      run: |
        python manage.py migrate
        pytest
