name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install conda
      uses: conda-incubator/setup-miniconda@v3
      with:
          python-version: 3.11
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: anaconda-client-env
          environment-file: environment.yml
    - name: Install Dependencies
      run: |
        pip install pytest
    - name: Run Tests
      run: |
        python manage.py migrate
        pytest
